### ISSUE TITLE
Can't display columns using add_layer and ColumnLayer

### ISSUE THREAD

**Issue by aluxh** [crazycapivara/deckgl#110]
I was trying to use add_layer function to display ColumnLayer, but nothing shows in the Shiny app.

```
    properties <- list(
        extruded = TRUE,
        radius = 100,
        elevationScale = 4,
        getElevation = JS("d => d.total_lots"),
        getPosition = JS("d => d.geometry"),
        getTooltip = JS("object => `${object.centroid.join(', ')}<br/>Count: ${object.points.length}`"),
        fixedTooltip = TRUE
    )

    output$distPlot <- renderDeckgl({
        deckgl(latitude = 1.3521, longitude = 103.8198, pitch = 45) %>%
            add_layer(class_name = "ColumnLayer", id="column-layer", data = sf, properties = properties) %>%
            add_mapbox_basemap(style = "mapbox://styles/mapbox/dark-v10")
    })
```

**Comment by crazycapivara** [comment]
Hi,
which version of _deckgl for R_ are you using? In version 0.1.8 which can be installed via _CRAN_, the _ColumnLayer_ is not supported, 'cause it uses version 6.2.4 of _deck.gl.js_ where the class was not yet available.

Therefore, you need to install the latest stable version via

```r
remotes::install_github("crazycapivara/deckgl")
```

In version 0.0.2 is already a _add_column_layer_ function included, so that you can run the examle:

```r
deckgl(zoom = 9, pitch = 35) %>%
  add_column_layer(
    data = bart_stations,
    diskResolution = 10,
    radius = 500,
    getPosition = ~lng + lat,
    getElevation = ~exits,
    getFillColor = JS("d => [48, 128, Math.sqrt(d.exits)]"),
    extruded = TRUE,
    getTooltip = ~name
  ) %>%
  add_mapbox_basemap()
```

And now there is also a shorter syntax to create _data accessors_ with `~property_name`, see also [NEWS.md](../blob/master/NEWS.md).

**Comment by aluxh** [comment]
I tried to install using github, but it gave me some errors related to db corruption. But, I just downloaded 0.22 and installed. And it works perfectly now.
